### ISSUE TITLE
[XCX] Nine Lives Segment

### ISSUE THREAD

**Issue by legrandgrand** [frontiernav/frontiernav#33]
Nine Lives is referenced as a Normal Mission on the Segment map while actually being an Affinity Mission

![nine lives](https://user-images.githubusercontent.com/38726488/48895857-65552380-ee46-11e8-892e-b9c608204532.png)

**Comment by legrandgrand** [comment]
Same goes for Renewed Will (next to MatchMaker at Central Melville Street, Commercial District

**Comment by jahed** [comment]
Thanks, looks like human error on my part. Even more reason to move over to using the datamine.

https://frontiernav.jahed.io/explore/xenoblade-chronicles-x/visualisations/map/entities/n229

**Comment by jahed** [comment]
Fixed in https://github.com/frontiernav/frontiernav-data/commit/2e972343380132c13a06b9d66fa12866112c9d56

I'm not sure what you meant by:

> Worth noting that there's also the Mira spot affected by those affinity missions are also labelled wrongly as Normal Missions

However, #34 will likely solve remaining data issues. Though it's a lot of work to switch over the datamine. XC2 is the current priority right now. XCX will be higher priority once a Switch port is announced as there'll be more new players needing help.

If anyone wants to fix XCX data issues while I'm occupied with XC2, feel free to checkout the data and look through it.

https://github.com/frontiernav/frontiernav-data/tree/master/games/xenoblade-chronicles-x
